before:
  hooks:
    - go mod tidy
builds:
  - id: dgate-server
    main: ./cmd/dgate-server
    binary: dgate-server
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
  - id: dgate-cli
    main: ./cmd/dgate-cli
    binary: dgate-cli
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - name_template: "dgate_{{ .Os }}_{{ .Arch }}"
    format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
