version: v1
debug: true
log_level: ${LOG_LEVEL:-info}
disable_default_namespace: true
tags:
  - debug
storage:
  type: file
  dir: .dgate/data/
test_server:
  port: 8888
  host: 0.0.0.0
  global_headers:
    X-Test-Header: ${TEST_HEADER:-test}
proxy:
  port: ${PORT:-80}
  host: 0.0.0.0
  enable_console_logger: true
  init_resources:
    namespaces:
      - name: "admin"
    services:
      - name: "admin-svc"
        namespace: "admin"
        urls: 
          - "http://localhost:9080"
    routes:
      - name: "admin-rt"
        paths: ["/*"]
        methods: ["*"]
        namespace: "admin"
        service: "admin-svc"
    domains:
      - name: "admin"
        namespace: "admin"
        patterns: ["admin.*"]
  tls:
    port: ${PORT_SSL:-443}
    auto_generate: true
    cert_file: internal/proxy/testdata/server.crt
    key_file: internal/proxy/testdata/server.key
admin:
  port: 9080
  host: 0.0.0.0
  allow_list:
    - "127.0.0.1/8"
    - "::1"

