version: v1
debug: true
log_level: ${LOG_LEVEL:-info}
disable_default_namespace: true
tags:
  - debug
storage:
  type: file
  dir: .dgate/data/
test_server:
  port: 8888
  host: 0.0.0.0
  global_headers:
    X-Node-Id: ${HOSTNAME:-N/A}
proxy:
  port: ${PORT:-80}
  host: 0.0.0.0
  enable_console_logger: true
  init_resources:
    namespaces:
      - name: "admin"
    services:
      - name: "admin-svc"
        namespace: "admin"
        urls: 
          - "http://localhost:9080"
    routes:
      - name: "admin-rt"
        paths: ["/*"]
        methods: ["*"]
        namespace: "admin"
        service: "admin-svc"
    domains:
      - name: "admin"
        namespace: "admin"
        patterns: ["admin.*"]
  tls:
    port: 443
    auto_generate: true
    cert_file: .lego/certificates/ufosoup.com.crt
    key_file: .lego/certificates/ufosoup.com.key
  client_transport:
    dns_server: 8.8.8.8:53
    dns_timeout: 10s
    max_conns_per_host: 1000
    max_idle_conns: 5000
    max_idle_conns_per_host: 1000
    idle_conn_timeout: 60s
    tls_handshake_timeout: 10s
    expect_continue_timeout: 5s
    max_response_header_bytes: 4096
    write_buffer_size: 4096
    read_buffer_size: 4096
    max_conns_per_client: 1000
    disable_keep_alives: false
    response_header_timeout: 10s
    dial_timeout: 10s
admin:
  port: 9080
  host: 0.0.0.0
  allow_list:
    - "127.0.0.1"
    - "127.0.0.1/8"
    - "::1"
  auth_method: null

