name: DGate E2E

on:
  push:
    branches: [ "**" ]
env:
  env_var: 
jobs:
  k6_load_test:
    name: k6 Load Test
    runs-on: ubuntu-latest
    env:
      PORT: 8080
      PORT_SSL: 8443
      PROXY_URL: http://localhost:8080
      ADMIN_URL: http://localhost:9080
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum
  
      - name: Build & Install
        run: |
          go mod download
          go build -v ./...
    
      - name: Install dgate-cli and dgate-server
        run: |
          go install github.com/dgate-io/dgate/cmd/dgate-cli
          dgate-cli --version
          go install github.com/dgate-io/dgate/cmd/dgate-server
          dgate-server --version
    
      - name: Install jq
        run: |
          sudo apt install -y jq
          jq --version

      - name: Start and wait 5 seconds
        run: go run cmd/dgate-server/main.go & sleep 5

      - name: Functional Standalone Tests
        run: |
          for i in functional-tests/admin_tests/*.sh; \
            do bash -c $i; done
      
