name: DGate Performance/Functional Test

on:
  push:
    branches: [ "**" ]
env:
  env_var: 
jobs:
  k6_load_test:
    name: k6 Load Test
    runs-on: ubuntu-latest
    env:
      PORT: 8080
      PORT_SSL: 8443
      PROXY_URL: http://localhost:8080
      ADMIN_URL: http://localhost:9080
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - run: go mod download

      - run: go run cmd/dgate-server/main.go &

      - name: Wait for server to start
        run: sleep 5
    
      - name: Install jq
        run: |
          sudo apt install -y jq
          jq --version
      
      - name: Functional Tests
        run: |
          for i in functional-tests/admin_tests/*.sh; \
            do bash -c $i; done
  
      - name: Run local k6 test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: performance-tests/perf-test.js
  
      
