name: DGate Performance Test (short)

on:
  push:
    branches: [ "**" ]

jobs:
  k6_load_test:
    name: k6 Load Test
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - run: |
          curl -SsL https://packages.httpie.io/deb/KEY.gpg | sudo gpg --dearmor -o /usr/share/keyrings/httpie.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/httpie.gpg] https://packages.httpie.io/deb ./" | sudo tee /etc/apt/sources.list.d/httpie.list > /dev/null
          sudo apt update
          sudo apt install httpie

      - run: go mod download

      - run: |
          export PORT=8080
          export PORT_SSL=8443
          go run cmd/dgate-server/main.go &

      - name: Wait for server to start
        run: sleep 5
      - run: |
          export PROXY_URL=http://localhost:8080
          ./functional-tests/admin_tests/performance_test_prep.sh
  
      - name: Run local k6 test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: performance-tests/perf-test.js

